# Generated by Django 3.2 on 2021-04-18 01:53

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLMap',
            fields=[
                ('short_url',
                 models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='short url')),
                ('original_url', models.TextField(verbose_name='original url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thirty_days_ago_check_date', models.DateTimeField(default=None, null=True)),
                ('seven_days_ago_check_date', models.DateTimeField(default=None, null=True)),
                ('current_day_check_date', models.DateTimeField(default=None, null=True)),
                ('cached_statistics', models.JSONField(default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform',
                 models.TextField(choices=[('Mobile', 'Mobile'), ('PC', 'PC'), ('Other', 'Other')], default='PC',
                                  max_length=8)),
                ('browser', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('url',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_shortener.urlmap')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['-created_at'], name='app_shorten_created_f2dbcc_idx'),
        ),
    ]
