# Generated by Django 3.2 on 2021-04-20 22:58

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='urlmap',
            index=django.contrib.postgres.indexes.HashIndex(fields=['short_url'],
                                                            name='app_shorten_short_u_0f8076_hash'),
        ),
    ]
