# Generated by Django 3.2 on 2021-04-20 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shortener', '0002_urlmap_app_shorten_short_u_0f8076_hash'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='urlmap',
            name='app_shorten_short_u_0f8076_hash',
        ),
    ]
